.INCLUDE "macros.inc"
.SEGMENT "LOADADDR"
	.WORD $0801
.SEGMENT "BASICSTUB"
	.WORD START-2
	.BYTE $00,$00,$9E
	.BYTE "2061"
	.BYTE $00,$00,$00
.SEGMENT "STARTUP"
START:
	JMP MAIN
.SEGMENT "CODE"

MAIN:
	JSR SETUP_VERA
	JSR LOAD_GRAPHICS
	RTS
SETUP_VERA:
	LDA #%01110001	;ENABLE SPRITES, LAYER_0, LAYER_1, AND SET TO VGA MODE
	STA VIDEO_CONFIG
	LDA #%01100010	;MAP HEIGHT/WIDTH 128X64 WITH 16 COLORS
	STA L0_CONFIG
	STA L1_CONFIG
	LDA #$00		;MAP 0 STORED AT $0:0000	
	STA L0_MAPBASE	
	LDA #$20		;MAP 1 STORED AT $0:4000
	STA L1_MAPBASE
	LDA #%01000011	;TILES STORED AT $1:0000
	STA L0_TILEBASE	
	STA L1_TILEBASE
	LDA #%00000101	;ENABLE VSYNC AND SPRITE COLLISION INTERRUPTS
	STA VERA_IEN	
	LDA #64			;SCALES THE SCREEN SIZE
	STA $9F2A
	STA $9F2B
	RTS
MAP_0_FILE:	.BYTE "map0.bin"
MAP_1_FILE:	.BYTE "map1.bin"
TILE_FILE:	.BYTE "tiles.bin"
SPRITE_FILE:.BYTE "sprite0.bin"
PALLETE_FILE:.BYTE "pal.bin"
LOAD_GRAPHICS:
	;MACRO LOAD_FILE (FILE LENGTH),(<FILE NAME),(>FILE NAME),(<LOAD LOCATION),(>LOAD LOCATION),(^LOAD LOCATION)
	LOAD_FILE #8,#<MAP_0_FILE,#>MAP_0_FILE,#$00,#$00,#$02			;LOAD MAP 0 TO $0:0000
	LOAD_FILE #8,#<MAP_1_FILE,#>MAP_1_FILE,#$00,#$40,#$02			;LOAD MAP 1 TO $0:4000
	LOAD_FILE #9,#<TILE_FILE,#>TILE_FILE,#$00,#$80,#$02			;LOAD THE TILESET TO $0:8000
	LOAD_FILE #11,#<SPRITE_FILE,#>SPRITE_FILE,#$00,#$00,#$03	;LOAD SPRITES TO $1:0000
	LOAD_FILE #7,#<PALLETE_FILE,#>PALLETE_FILE,#$00,#$FA,#$03	;LOAD THE PALLETE TO $1:FA00
	RTS
DEFAULT_IRQ: .ADDR 0
IRQ_HANDLING:
	INIT_IRQ:	
		LDA IRQVEC
		STA DEFAULT_IRQ
		LDA IRQVEC+1
		STA DEFAULT_IRQ+1
		SEI
		LDA #<CUSTOM_IRQ
		STA IRQVEC
		LDA #>CUSTOM_IRQ
		STA IRQVEC+1
		CLI
		RTS
	CUSTOM_IRQ:
		JSR VSYNC_IRQ
		JSR COLLISION_IRQ
		JMP (DEFAULT_IRQ)
	VSYNC_IRQ:
		LDA VERA_ISR
		AND #$01
		BNE UPDATE_SCREEN
		RTS
	UPDATE_SCREEN:
		JSR MOUSE_GET
		RTS
	COLLISION_IRQ:
		AND #$04
		BNE SPRITE_COLLISION
		RTS
	SPRITE_COLLISION:
		RTS